### ISSUE TITLE
Configure CLI from file using TOML package

### ISSUE THREAD

**Issue by sacha-c** [elementsinteractive/sheriff#32]
**Is your feature request related to a problem? Please describe.**
The go-cli package we use can configure the CLI from file ([see here](https://cli.urfave.org/v3/examples/flags/#values-from-alternate-input-sources-yaml-toml-and-others)) but it is quite limited. It doesn't support all of TOML syntax

**Describe the solution you'd like**
I would like to have more extensive TOML syntax support to configure the CLI, to allow a neater configuration file which could look like this one (leveraging dictionaries for instance):
```toml
[report.to]
email = ""
slack-channel = ""

[report.issue.text_replacements] # or similar
main_header = "> this md will appear just below the issue title"
sections = {
   acknowledged = "> this will only appear in the ack section"
}
```

We could use the go toml package https://github.com/pelletier/go-toml, which we already use to parse the project-level configuration

**Describe alternatives you've considered**
...

**Additional context**
...
